import os
import re


DOCS_DIR = "core/docs"
README_PATH = os.path.join(DOCS_DIR, "README.md")
ROOT_INDEX_PATH = "index.md"
MKDOCS_PATH = "mkdocs.yml"
MARKER_START = "<!-- MODULES_START -->"
MARKER_END = "<!-- MODULES_END -->"


def _is_docs_module_dir(path: str) -> bool:
    if not os.path.isdir(path):
        return False
    name = os.path.basename(path)
    return not name.startswith(".") and name != "templates"


def _find_main_doc(folder_path: str, folder_name: str) -> str | None:
    priorities = [
        f"{folder_name}.md",
        "00_main.md",
        "README.md",
        "index.md",
    ]

    for candidate in priorities:
        full = os.path.join(folder_path, candidate)
        if os.path.exists(full):
            return candidate

    md_files = [f for f in os.listdir(folder_path) if f.lower().endswith(".md")]
    if not md_files:
        return None
    md_files.sort(key=len)
    return md_files[0]


def _get_title(file_path: str) -> str | None:
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip().startswith("# "):
                    return line.strip().replace("# ", "").strip()
    except Exception:
        return None
    return None


def _generate_modules():
    if not os.path.isdir(DOCS_DIR):
        return []

    modules = []
    for entry in sorted(os.listdir(DOCS_DIR)):
        folder_path = os.path.join(DOCS_DIR, entry)
        if not _is_docs_module_dir(folder_path):
            continue

        main_file = _find_main_doc(folder_path, entry)
        if not main_file:
            continue

        full_path = os.path.join(folder_path, main_file)
        title = _get_title(full_path)
        display_name = title if title else entry.replace("_", " ").title()

        modules.append(
            {
                "folder": entry,
                "name": display_name,
                "rel_path_core": f"./{entry}/{main_file}",
                "rel_path_root": f"core/docs/{entry}/{main_file}",
            }
        )

    return modules


def _update_core_readme(modules):
    if not os.path.exists(README_PATH):
        return

    with open(README_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    list_items = [f"- [{m['name']}]({m['rel_path_core']})" for m in modules]

    new_section = f"{MARKER_START}\n"
    new_section += "<!-- This section is automatically generated by .github/scripts/update-docs-index.py -->\n\n"
    new_section += "\n".join(list_items)
    new_section += f"\n\n{MARKER_END}"

    pattern = re.compile(
        f"{re.escape(MARKER_START)}.*?{re.escape(MARKER_END)}",
        re.DOTALL,
    )

    if pattern.search(content):
        new_content = pattern.sub(new_section, content)
        with open(README_PATH, "w", encoding="utf-8") as f:
            f.write(new_content)


def _update_root_index(modules):
    content = "# Índice de Documentación\n\n"
    content += "<!-- This file is automatically generated by .github/scripts/update-docs-index.py -->\n\n"
    for m in modules:
        content += f"*   [{m['name']}]({m['rel_path_root']})\n"
    content += "\n---\n"
    content += "*Para ver todos los archivos, navega a [core/docs/](core/docs/).*\n"

    with open(ROOT_INDEX_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    modules = _generate_modules()
    _update_core_readme(modules)
    _update_root_index(modules)

    if os.path.exists(MKDOCS_PATH):
        return


if __name__ == "__main__":
    main()

