# Ka0s Blog Configuration

title: Ka0s Engineering Blog
email: hello@ka0s.io
description: >- # this means to ignore newlines until "baseurl:"
  Engineering Platform & Cloud Native Knowledge Base.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ka0s.io" # the base hostname & protocol for your site
twitter_username: ka0s_io
github_username:  Ka0s-Klaus

# Logo
title-img: "/assets/img/logo-ka0s.png"
avatar: "/assets/img/kaos-daavid-2.png"
round-avatar: false

# Build settings
markdown: kramdown
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap

# i18n Configuration (Future Proofing)
languages: ["en", "es"]
default_lang: "es"
exclude_from_localizations: ["javascript", "images", "css"]

# Navigation
navbar-links:
  About Me: "aboutme"
  Resources:
    - Ka0s Core: "https://github.com/Ka0s-Klaus/ka0s"
    - Web: "https://www.ka0s.io"
  Tags: "tags"

# Footer
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Ka0s-Klaus/ka0s
  instagram:
  linkedin:
  pinterest:
  rss: rss
  stackoverflow:
  tumblr:
  twitter:
  youtube:
